travis:
  secure:
    BINSTAR_TOKEN: BpRLPyof4lm2X/i6wKP3fC3ZNWfbo8ekPtR1zyntGkXL8k7BNlxuENSs2JVVY1deEJwOO+RyssiEJob0cDKXKIezm0JtJbjbJsOPhNxBNwW6uae9n274M+DMVPgvcZMVP6AHYVILKCocX4K58g4De3FNN25oR3eIn8+N8JYElG392eurfkKnQVVVmT95/QGryCwhuBBSOjeqE22iDanWUpxIbNCQiDn3QPe5MGfD8queX8MoEfUd4iRXgQTnHfDPMUGEIvpE/56eqpr1Ef8b65+ORld+vJ5yYvb4Zw6cMWCXg242UTYfitRdm6zHp6sGztVnj6z/aHYo8jci0Fx6RKD/OyNO7/0h883LJCDuOIKaAmEmWZEecIVd6gHnpZzHSo6f9rw0xP6RjSrEcPYIS09FFJ+rwlwA/4c90nVtj76kq4hTRViKsPq1MTQgJEcBKknSLw4MVrdwm0BglGGbyI0nvdvLo2LE6+y6zOWR2fWt5mCCsiDePCnz05+thLnpslioHPSmSQPzBKhs1/PPbWVxrgyAPJVNrbpwj6cHci20j6qUTvy5o80Sx6GoMC6xEfbnnfMuQz7zSHA0e++TrnzTdHJEiAxyFH/edoUsoRhxFq9kXW118xgubc75TIrNNx5eHBLGdVFFb62aAEq45u8f/h670iNsipvEy+MsNmI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
